# =========================================================
# APLICACIÓN
# =========================================================

spring.application.name=api-para-reservas-de-restauranteUES

server.port=8081


# =========================================================
# BASE DE DATOS - POSTGRESQL
# =========================================================

spring.datasource.url=jdbc:postgresql://localhost:5433/reservas_restaurante
spring.datasource.username=${RESERVAS_DB_USERNAME}
spring.datasource.password=${RESERVAS_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# =========================================================
# JPA / HIBERNATE
# =========================================================

# Hibernate NO debe modificar la estructura de PostgreSQL.
# Solo verifica que las entidades Java sean compatibles con la BD.
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true


# =========================================================
# SCHEMA
# =========================================================

spring.jpa.properties.hibernate.default_schema=reservas