# Nombre de la aplicación
spring.application.name=api-para-reservas-de-restauranteUES

# Puerto del servidor web
server.port=8080

# Configuración de la base de datos H2 (en memoria)
spring.datasource.url=jdbc:h2:mem:reservasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configuración de JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true